name: CI

on:
    push:
        branches:
            - main

jobs:
    tests:
        name: Tests
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            version:
              - '1'
              - '1.10'
              - '1.11'
            os:
              - ubuntu-latest
            arch:
              - x64
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Julia
              uses: julia-actions/setup-julia@v1
              with:
                version: ${{ matrix.version }}
                arch: ${{ matrix.arch }}

            - name: Run tests
              uses: julia-actions/julia-runtest@v1
              env:
                  JULIA_NUM_THREADS: 2